### PR TITLE
Remove PMs and move scripts to lib

### PR DESCRIPTION
**Pull request by zachthompson**
* Remove Perl modules,  which only served to hold metadata which is no longer necessary.
* Move processing scripts to lib/ since they aren't really shared and would conflict with js/css if/when we allow templating.

### CODE REVIEW

**Comment by jdorweiler** [comment]
:+1:

**Comment by GuiltyDolphin** [comment]
@zachthompson The `lib` directory is `longtail`, rather than `LongTail` - is this intentional?

Re: #53.

**Comment by zachthompson** [comment]
@GuiltyDolphin Yes, it's just `share/longtail` migrated to 'lib/longtail'.

**Comment by GuiltyDolphin** [comment]
@zachthompson Okay! We may want to update the files on the Platform then.

**Comment by zachthompson** [comment]
@GuiltyDolphin Good catch.  Looking into with @jdorweiler.  We'll get it done...somehow. :dart:

**Comment by GuiltyDolphin** [comment]
@zachthompson @fzzr- [Noticed the broken links](https://github.com/duckduckgo/zeroclickinfo-longtail/issues/53), but good to hear!

**Pull request merged**
