### PR TITLE
Fix to scraping for Climbing IA

### PR DESCRIPTION
**Pull request by kfloey**
The Climbing data from thecrag.com can now be scraped from the world page

### CODE REVIEW

**Comment by kfloey** [comment]
@jdorweiler Sorry for such the late fix; I totally missed your comment... I'm not sure how often you scrape, but I hope this quick fix adds some convenience.

**Comment by jdorweiler** [comment]
@kfloey no problem! thanks for coming back to it :smile:
I'm planning on updating some longtail data soon so I'll test it out then.

**Comment by kfloey** [comment]
@jdorweiler Thanks! Let me know how it goes.

Just wondering, has there been any change to the format of the instant answers?  I remember you mentioning that sometime more functionality/format options would come to longtail answers.

**Comment by jdorweiler** [comment]
@kfloey There is!  We're actually almost done making a new IA to test that out.  If you're interested trying to build one I can ping when we're ready.

**Comment by kfloey** [comment]
@jdorweiler Yeah, I'd be interested! Let me know when its ready

**Comment by jdorweiler** [comment]
@kfloey sorry I forgot to update you on this :frowning:  
I ran the new code and updated the live data last week.  Everything looked great. 

Adding the new longtail features is still in progress.  We're playing with a few different ways to do it so I'm not sure how much longer it might be.  I'll  ping you when we have something figured out though.

**Pull request merged**
