### PR TITLE
EPA Fuel Economy Longtail

### PR DESCRIPTION
**Pull request by zachthompson**
**What does your Instant Answer do?**
Longtail for EPA Fuel Economy data (converted from https://github.com/duckduckgo/zeroclickinfo-fathead/pull/100) Downloads source, parses it, and creates output.xml

**What problem does your Instant Answer solve (Why is it better than organic links)?**
-Displays city/hwy fuel economy directly.
-Gives ranges for city/hwy for models with multiple vehicle configurations
-Lists individual model configuration fuel economies.

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://www.fueleconomy.gov/feg/epadata/vehicles.csv.zip

**Why did you choose this data source?**
Suggested in idea request

**Are there any other alternative (better) data sources?**
Not that I found with comprehensive fuel economy data.

**What are some example queries that trigger this Instant Answer?**
2011 Honda Fit fuel economy
2011 Honda Fit mpg (this could optional)

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Anyone researching mileage for a vehicle

**Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?**
Yes - https://duck.co/ideas/idea/4514/vehicle-fuel-efficiency

**Which existing Instant Answers will this one supercede/overlap with?**
None that I know of.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

See screenshots in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/100

Checklist

Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information
[] Wrote test file and added to t/ directory
[x] Verified that Instant Answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that Instant Answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility
    Please let us know which browsers/devices you've tested on:
    N/A
```

### CODE REVIEW

**Comment by jdorweiler** [comment]
@zachthompson could you remove the space between the mpg line?  It's ready to go after that.

**Comment by zachthompson** [comment]
@jdorweiler @chrismorast Check also the vehicles that have the note about passenger/luggage volumes, e.g. 1993 Volkswagen Golf III/GTI.  I put an extra newline to offset the note.  Let me know if you want to compress that as well.

**Comment by jdorweiler** [comment]
@zachthompson thanks, let's remove that space too.

**Comment by jdorweiler** [comment]
@zachthompson Thanks! :cake: 
I'll ping you when it's live

**Pull request merged**
